### PR TITLE
Feat: add ical file support for daily planner

### PR DESCRIPTION
**Pull request by ipapast**
This PR adds a basic event display on the daily planner. It renders like this:

image

What it acutally does:
- adds a flag ICAL where a user can point to an `.ical` file location.
- loads the ical file, parses it, and displays them in the daily planner template.
- adds a test for the calendar parser

The daily planner Notes are shrunk a bit so that we can get a few events in the same space.
I have chosen to only include events that have a UTC timestamp (with 'Z') as handling all cases manually and getting timezones in regard is hard. Maybe that can be an additional feature.

# How to run:
```
PLANNER_YEAR=2024 \
PASSES=1 \
CFG="cfg/base.yaml,cfg/template_breadcrumb.yaml,cfg/sn_a5x.breadcrumb.default.yaml" \
NAME="sn_a5x.breadcrumb.default" \
ICSFILE="app/components/icsparser/example_calendar.ics" \ 
./single.
```

Any comments on making it better/easier are welcome

### CODE REVIEW

**Comment by kudrykv** [comment]
Hi @ipapast!
Can you please check out `rubify` branch?
Ultimately, I want to upgrade the repository to that version.
Could you please estimate how hard would it be to implement ical there?

**Comment by ipapast** [comment]
> Hi @ipapast! Can you please check out `rubify` branch? Ultimately, I want to upgrade the repository to that version. Could you please estimate how hard would it be to implement ical there?

Hey, I'll have a look today and let you know :)

**Comment by ipapast** [comment]
> Hi @ipapast! Can you please check out `rubify` branch? Ultimately, I want to upgrade the repository to that version. Could you please estimate how hard would it be to implement ical there?

Alright, I need to re-work this PR because I have forked `main` only. I will fork the entire repo again, so possibly this PR will be closed. I will open a new one after, if that happens.

**Comment by philipsd6** [comment]
Personally, I'd rather have the ical data put right in the schedule, and leave the notes section for notes! But I obviously understand that's a more significant challenge...

**Comment by ipapast** [comment]
> Personally, I'd rather have the ical data put right in the schedule, and leave the notes section for notes! But I obviously understand that's a more significant challenge...

that would be much better, I agree. 

I closed this PR as I need to work on a ruby branch version of it, so it might take some time, but the idea is here, and someone can re-work it if needed.

**Comment by kudrykv** [comment]
Thank you for your idea and your work
I might take look into it next month. The idea looks interesting

However, calendar events are very much fleeting. Aside from putting some birthdays and holidays, I don't see a convenient way to flush new events into the planner and syncing it back to the device where it's being used

**Pull request closed without merging**
